### ISSUE TITLE
不只是什么，小白一个，，，求解惑

### ISSUE THREAD

**Issue by TSLlemon** [mli/autocut#130]
Traceback (most recent call last):
  File "\\?\C:\ProgramData\anaconda3\Scripts\autocut-script.py", line 33, in <module>
    sys.exit(load_entry_point('autocut-sub==1.1.0', 'console_scripts', 'autocut')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\autocut\main.py", line 191, in main
    from .daemon import Daemon
  File "C:\ProgramData\anaconda3\Lib\site-packages\autocut\daemon.py", line 7, in <module>
    from . import cut, transcribe, utils
  File "C:\ProgramData\anaconda3\Lib\site-packages\autocut\cut.py", line 6, in <module>
    from moviepy import editor
ImportError: cannot import name 'editor' from 'moviepy' (C:\Users\tsl\AppData\Roaming\Python\Python312\site-packages\moviepy\__init__.py)

**Comment by QiongsK** [comment]
just import 'moviepy' not 'moviepy.editor'

**Comment by Zhao-yangyang** [comment]
I ran into a similar problem：
Traceback (most recent call last):
  File "/Users/miniconda3/bin/autocut", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/miniconda3/lib/python3.12/site-packages/autocut/main.py", line 191, in main
    from .daemon import Daemon
  File "/Users/miniconda3/lib/python3.12/site-packages/autocut/daemon.py", line 7, in <module>
    from . import cut, transcribe, utils
  File "/Users/miniconda3/lib/python3.12/site-packages/autocut/cut.py", line 6, in <module>
    from moviepy import editor
ImportError: cannot import name 'editor' from 'moviepy' (/Users/miniconda3/lib/python3.12/site-packages/moviepy/__init__.py)

**Comment by chenqianhe** [comment]
I suspect there might be a version issue causing the import differences. Could you please check this package and see if there are any differences in the import methods?
