### ISSUE TITLE
在M2 Macbook Pro上使用时局部报错

### ISSUE THREAD

**Issue by lovelystrange** [mli/autocut#38]
[autocut:transcribe.py:L24] INFO   Transcribing IMG_8103.MOV
100%|█████████████████████████████████████| 72.1M/72.1M [00:12<00:00, 6.07MiB/s]
/Users/@/Library/Python/3.9/lib/python/site-packages/whisper/transcribe.py:78: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
[autocut:transcribe.py:L81] INFO   Done transcription in 15.4 sec
[autocut:transcribe.py:L35] INFO   Transcribed IMG_8103.MOV to IMG_8103.srt
Traceback (most recent call last):
  File "/Users/@/Library/Python/3.9/bin/autocut", line 8, in <module>
    sys.exit(main())
  File "/Users/@/Library/Python/3.9/lib/python/site-packages/autocut/main.py", line 51, in main
    Transcribe(args).run()
  File "/Users/@/Library/Python/3.9/lib/python/site-packages/autocut/transcribe.py", line 36, in run
    self._save_md(name + '.md', output, input)
  File "/Users/@/Library/Python/3.9/lib/python/site-packages/autocut/transcribe.py", line 118, in _save_md
    md.add_done_edditing(False)
AttributeError: 'MD' object has no attribute 'add_done_edditing'

---

最终可以获得SRT字幕文件，但没有MD文件。

**Comment by Rukhx** [comment]
我也出现这个问题，应该是由于代码错误
将“add_done_edditing”修改为“add_done_editing”后，MD文件正常生成

**Comment by zcf0508** [comment]
https://github.com/mli/autocut/pull/37

**Comment by mli** [comment]
merged。升级安装一下就行。如果还有错，请reopen issue。
