### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position  37-47: character maps to <undefined>

### ISSUE THREAD

**Issue by ArmandXiao** [mli/autocut#5]
测试环境，windows miniconda
```
torch                     1.11.0+cu113             pypi_0    pypi 
```
- **个别**文件报错，其他的可以运行。
---

![image](https://user-images.githubusercontent.com/45375764/200474484-194c80b0-2073-427f-8cc0-385eb60618bd.png)

---

```
(torch_env) C:\Users\User\Videos\nn>autocut -t visualization.mkv
[autocut:transcribe.py:L24] INFO   Transcribing visualization.mkv
[autocut:transcribe.py:L81] INFO   Done transcription in 8.5 sec
Traceback (most recent call last):
  File "E:\miniconda\envs\torch_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\miniconda\envs\torch_env\lib\runpy.py", line 87, in _run_code    exec(code, run_globals)
  File "E:\miniconda\envs\torch_env\Scripts\autocut.exe\__main__.py", line 7, in <module>
  File "E:\miniconda\envs\torch_env\lib\site-packages\autocut\main.py", 
line 41, in main
    Transcribe(args).run()
  File "E:\miniconda\envs\torch_env\lib\site-packages\autocut\transcribe.py", line 34, in run
    self._save_srt(output, transcribe_results)
  File "E:\miniconda\envs\torch_env\lib\site-packages\autocut\transcribe.py", line 110, in _save_srt
    f.write(srt.compose(subs))
  File "E:\miniconda\envs\torch_env\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]   
UnicodeEncodeError: 'charmap' codec can't encode characters in position 
37-47: character maps to <undefined>
```

**Comment by mli** [comment]
在encode里加上 `ignore`。你试一试是不是解决了问题？如果没有的话，请reopen issue

https://github.com/mli/autocut/commit/0b0f87a16871a5fff105f64c24f57f37669796b4

**Comment by ArmandXiao** [comment]
> 在encode里加上了 `ignore`，忽略掉不认识的编码。你试一试是不是解决了问题？如果没有的话，请reopen issue
> 
> [0b0f87a](https://github.com/mli/autocut/commit/0b0f87a16871a5fff105f64c24f57f37669796b4)

多谢沐神，问题解决了。

还有一个小问题👇导致安装时候报错
> [setup.py](https://github.com/mli/autocut/blob/main/setup.py)
> line11: init_fn = os.path.join(os.path.dirname(__file__), 'autcut', '__init__.py')
- `autcut` $\to$ `autocut`

**Comment by mli** [comment]
多谢指出，fix了 https://github.com/mli/autocut/commit/d73c7c05739914b7d5508bb757ae45fe3f0d274b
