### ISSUE TITLE
总是找不到文件？

### ISSUE THREAD

**Issue by 1358467720** [mli/autocut#55]
如下我给了绝对地址还是依旧报错，是为什么呢？
```
(deep_learning) D:\all_codes\deep_learning\autocut\video>autocut -t D:\all_codes\deep_learning\autocut\video
[autocut:transcribe.py:L24] INFO   Transcribing D:\all_codes\deep_learning\autocut\video
Traceback (most recent call last):
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\Scripts\autocut.exe\__main__.py", line 7, in <module>
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\autocut\main.py", line 96, in main
    Transcribe(args).run()
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\autocut\transcribe.py", line 29, in run
    audio = whisper.load_audio(input, sr=self.sampling_rate)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\whisper\audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by zcf0508** [comment]
监听目录用 -d 参数， -t 参数是直接处理单个文件的

**Comment by 1358467720** [comment]
现在是文件了 还是有错
```
(deep_learning) D:\all_codes\deep_learning\you-get\src\you_get>autocut -t D:\all_codes\deep_learning\autocut\video\1.mp4
[autocut:transcribe.py:L24] INFO   Transcribing D:\all_codes\deep_learning\autocut\video\1.mp4
Traceback (most recent call last):
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\Scripts\autocut.exe\__main__.py", line 7, in <module>
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\autocut\main.py", line 96, in main
    Transcribe(args).run()
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\autocut\transcribe.py", line 29, in run
    audio = whisper.load_audio(input, sr=self.sampling_rate)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\whisper\audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\songHat\miniconda3\envs\deep_learning\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

```

**Comment by zcf0508** [comment]
看着像是没装 [ffmpeg](https://ffmpeg.org/)

**Comment by 1358467720** [comment]
应该都装好了？
@zcf0508 
![image](https://user-images.githubusercontent.com/48643755/203716377-27e6cc25-40fb-4735-b90b-16681288d8fb.png)

**Comment by Guohui-Peng** [comment]
关了窗口生新进入试试。安装完成PATH路径不会重新加载，要重新进终端。

**Comment by 1358467720** [comment]
感谢，我今天重启，再重新pip安装成功了
