### ISSUE TITLE
转录视频出现报错

### ISSUE THREAD

**Issue by oyb1125** [mli/autocut#80]
如图 这个视频六分钟，我转录一分钟的视频的时候就可以，这是什么原因？视频太大了吗

![2023-03-10 10-06-35屏幕截图](https://user-images.githubusercontent.com/62881198/224204980-866299fd-9eb1-435e-aa0b-613d1d74dc3c.png)

**Comment by FIFCOM** [comment]
由于网络不佳，从Github上加载VAD模型时失败：[transcribe.py#L65](https://github.com/mli/autocut/blob/main/autocut/transcribe.py#L65 "transcribe.py#L65")
```
[autocut:transcribe.py:L37] INFO   Transcribing ./video/1.mp4
Traceback (most recent call last):
  File "/opt/conda/bin/autocut", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/autocut/main.py", line 119, in main
    Daemon(args).run()
  File "/opt/conda/lib/python3.9/site-packages/autocut/daemon.py", line 18, in run
    self._iter()
  File "/opt/conda/lib/python3.9/site-packages/autocut/daemon.py", line 34, in _iter
    transcribe.Transcribe(args).run()
  File "/opt/conda/lib/python3.9/site-packages/autocut/transcribe.py", line 48, in run
    speech_timestamps = self._detect_voice_activity(audio)
  File "/opt/conda/lib/python3.9/site-packages/autocut/transcribe.py", line 65, in _detect_voice_activity
    self.vad_model, funcs = torch.hub.load(
  File "/opt/conda/lib/python3.9/site-packages/torch/hub.py", line 555, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/opt/conda/lib/python3.9/site-packages/torch/hub.py", line 199, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "/opt/conda/lib/python3.9/site-packages/torch/hub.py", line 142, in _parse_repo_info
    with urlopen(f"https://github.com/{repo_owner}/{repo_name}/tree/main/"):
  File "/opt/conda/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/opt/conda/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/conda/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/conda/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/opt/conda/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/opt/conda/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/opt/conda/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

## 解决方法

使用代理：

  - 设置环境变量：`export HTTP_PROXY="http://localhost:10809"`
  
  - 或 开启Clash的 `TUN模式`
